### PR TITLE
Release v2.0.0

### PR DESCRIPTION
**Pull request by lucianosz7**

### CODE REVIEW

**Comment by lucianosz7** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- seeds.py  1
- app/forms.py  1
- api/env.py  2
         

Clones added
============
- api/settings.py  2
- api/dev.py  3
- api/prod.py  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/2019.2-ArBC-API/2019.2-ArBC-API/pullRequest?prid=4582731&bid=15392301)

**Comment by lucianosz7** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
           

Complexity increasing per file
==============================
- seeds.py  1
- app/forms.py  1
- api/env.py  2
         

Clones added
============
- api/settings.py  2
- api/dev.py  3
- api/prod.py  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/2019.2-ArBC-API/2019.2-ArBC-API/pullRequest?prid=4582731&bid=15392301)

**Comment by lucianosz7** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- api/env.py  2
- app/forms.py  1
- seeds.py  1
         

Clones added
============
- api/dev.py  3
- api/settings.py  2
- api/prod.py  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/2019.2-ArBC-API/2019.2-ArBC-API/pullRequest?prid=4582731&bid=15392301)

**Comment by lucianosz7** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- seeds.py  1
- app/forms.py  1
- api/env.py  2
         

Clones added
============
- api/settings.py  2
- api/prod.py  3
- api/dev.py  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/2019.2-ArBC-API/2019.2-ArBC-API/pullRequest?prid=4582731&bid=15392301)

**Comment by lucianosz7** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- seeds.py  1
- app/forms.py  1
- api/env.py  2
         

Clones added
============
- api/prod.py  3
- api/settings.py  2
- api/dev.py  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/2019.2-ArBC-API/2019.2-ArBC-API/pullRequest?prid=4582731&bid=15392301)

**Comment by lucianosz7** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- seeds.py  1
- app/forms.py  1
- api/env.py  2
         

Clones added
============
- api/dev.py  3
- api/settings.py  2
- api/prod.py  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/2019.2-ArBC-API/2019.2-ArBC-API/pullRequest?prid=4582731&bid=15392301)

**Review by eilimrib — APPROVED** [review]
Release 2, lá vamos nós!

**Pull request merged**
